// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface ICatalogFields {
  /** id */
  id?: string | undefined;

  /** name */
  name: string;

  /** taxonomies */
  taxonomies: ITaxonomy[];
}

export interface ICatalog extends Entry<ICatalogFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "catalog";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICountryFields {
  /** name */
  name: string;

  /** code */
  code: string;

  /** market */
  market?: string | undefined;

  /** catalog */
  catalog: ICatalog;

  /** region */
  region?: Entry<{ [fieldId: string]: unknown }> | undefined;

  /** languages */
  languages?: Entry<{ [fieldId: string]: unknown }>[] | undefined;
}

export interface ICountry extends Entry<ICountryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "country";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILanguageFields {
  /** name */
  name?: string | undefined;

  /** code */
  code?: string | undefined;

  /** catalog */
  catalog?: Entry<{ [fieldId: string]: unknown }> | undefined;
}

export interface ILanguage extends Entry<ILanguageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "language";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IProductFields {
  /** Name */
  name: string;

  /** Description */
  description?: string | undefined;

  /** Slug */
  slug: string;

  /** Reference */
  reference?: string | undefined;

  /** Images */
  images?: Asset[] | undefined;

  /** Variants */
  variants?: IVariant[] | undefined;
}

export interface IProduct extends Entry<IProductFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "product";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IRegionFields {
  /** name */
  name?: string | undefined;
}

export interface IRegion extends Entry<IRegionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "region";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISizeFields {
  /** Name */
  name: string;
}

export interface ISize extends Entry<ISizeFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "size";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITaxonFields {
  /** id */
  id?: string | undefined;

  /** label */
  label?: string | undefined;

  /** description */
  description?: string | undefined;

  /** slug */
  slug?: string | undefined;

  /** name */
  name: string;

  /** references */
  references?: IProduct[] | undefined;

  /** taxons */
  taxons?: Entry<{ [fieldId: string]: unknown }>[] | undefined;
}

export interface ITaxon extends Entry<ITaxonFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "taxon";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITaxonomyFields {
  /** id */
  id?: string | undefined;

  /** name */
  name: string;

  /** facetKey */
  facetKey?: string | undefined;

  /** taxons */
  taxons: ITaxon[];
}

export interface ITaxonomy extends Entry<ITaxonomyFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "taxonomy";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVariantFields {
  /** Name */
  name: string;

  /** Code */
  code: string;

  /** Description */
  description?: string | undefined;

  /** Images */
  images?: Asset[] | undefined;

  /** Size */
  size: ISize;
}

export interface IVariant extends Entry<IVariantFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "variant";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "catalog"
  | "country"
  | "language"
  | "product"
  | "region"
  | "size"
  | "taxon"
  | "taxonomy"
  | "variant";

export type IEntry =
  | ICatalog
  | ICountry
  | ILanguage
  | IProduct
  | IRegion
  | ISize
  | ITaxon
  | ITaxonomy
  | IVariant;

export type LOCALE_CODE = "en" | "it";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en";
